### ISSUE TITLE
Add a benchmark to compare fqfa to other python fastx parser

### ISSUE THREAD

**Issue by natir** [CountESS-Project/fqfa#3]
Even though fqfa is written purely in python and will probably be slower than alternatives that use C modules. 

It would be interesting for the reader/user to have a small benchmark, on two or three files that correspond to the fqfa usage. The reader/user can then have an idea of which impact fqfa can have on its performance compared to the alternatives.

Thanks for your work.

Just to help editor to flow this issue openjournals/joss-reviews#2076

**Comment by afrubin** [comment]
Thank you for this feedback. I've added a new page to the documentation that includes some usage examples and timing information for fqfa and pyfastx.

It's available at the following branch: https://github.com/CountESS-Project/fqfa/tree/benchmark

**Comment by natir** [comment]
Ok thanks, it could by intresting to include this result in paper.

**Comment by afrubin** [comment]
Good suggestion, I've added this result to the paper and merged into master.

**Comment by natir** [comment]
Ok for me it's perfect
