### ISSUE TITLE
A couple of questions / suggestions

### ISSUE THREAD

**Issue by FlorianThibord** [CountESS-Project/fqfa#7]
This is my first review for joss (https://github.com/openjournals/joss-reviews/issues/2076), and I'm not sure of where to put my comments, so I'll do it here:

The code is well written, in pure python, understandable, well documented, and maybe most importantly, this package can be easily used in a python project and does not require dependencies.

The use of modern python 3 functionalities such as f-strings, dataclass module, and type hinting sets it apart from the many implementations of fasta/fastq parsers available.

I only have a question and a suggestion:
 1- Why is there a function to write fasta records, but not a function to write fastq reads?
 2- I think pyfaidx only deals with fasta, not fastq, so it might not be relevant. Maybe mention Fastaq (https://github.com/sanger-pathogens/Fastaq) instead?

Otherwise, well done it's a great work!

**Comment by afrubin** [comment]
Thank you for the thoughtful review!

> 1- Why is there a function to write fasta records, but not a function to write fastq reads?

The `FastqRead.__str__()` method writes FASTQ records, so it didn't make sense to me to add an additional function. I have added text to the documentation where the FASTQ reader functions are described to clarify this usage.

> 2- I think pyfaidx only deals with fasta, not fastq, so it might not be relevant. Maybe mention Fastaq (https://github.com/sanger-pathogens/Fastaq) instead?

Thank you for pointing out Fastaq. I've added a citation to the manuscript.

**Comment by FlorianThibord** [comment]
Ok, thanks for the clarification!
